title: Machine Learning and Computation Statistics
logo: /images/logo.png
description: This is a teaching partnership between the Africa Center of Excellence in Data Science at the University of Rwanda and the Institute of Applied Computational Science at Harvard University.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
