title: DSC6232 Machine Learning and Computation Statistics
logo: /images/logo.png
description: This is a first course in machine learning. This course covers the fundamental concepts of machine learning, including - classification, regression, dimensionality reduction, clustering and elements of deep learning. The course has dual focus on key mathematical concepts underlying machine learning models and on the application of machine learning algorithms on real-world data science problems. This course serves as a foundation for students who are interested in advanced courses and further independent study in the field of machine learning and data science.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
