title: DSC6232 Machine Learning and Computation Statistics
logo: /images/logo.png
description: This is a first course in machine learning. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
